from resources.structures.Bloxlink import Bloxlink # pylint: disable=import-error
from resources.constants import RELEASE # pylint: disable=import-error
from resources.exceptions import Error, Message # pylint: disable=import-error
from io import StringIO
from discord.errors import Forbidden, NotFound
from discord import File
import asyncio
import math
import datetime

loop = asyncio.get_event_loop()


extract_accounts = Bloxlink.get_module("roblox", attrs=["extract_accounts"])


@Bloxlink.command
class BanSearchCommand(Bloxlink.Module):
    """scan your server for ban-evaders"""

    def __init__(self):
        self.permissions = Bloxlink.Permissions().build("BLOXLINK_MODERATOR")
        self.arguments = [
            {
                "prompt": "This command will scan your server members for members with Roblox accounts which correspond to banned members of your server.\n\n"
                          "Would you like to **ban** ban-evaders, **kick** them, or do **nothing**?\n\nI will provide a list of members if you choose the ``nothing`` option.",
                "type": "choice",
                "name": "action",
                "choices": ("kick", "ban", "nothing")
            }
        ]
        self.category = "Premium"
        self.REDIS_COOLDOWN_KEY = "guild_scan:{id}"

    async def process_guild(self, guild, author, action, response):
        if not guild.chunked:
            try:
                await guild.chunk()
            except:
                pass

        await response.send("A scan has now been started.")

        try:
            redis_cooldown_key = self.REDIS_COOLDOWN_KEY.format(release=RELEASE, id=guild.id)
            await self.redis.set(redis_cooldown_key, 2, ex=86400)

            ban_evaders = {}

            try:
                bans = await guild.bans()
            except Forbidden:
                raise Error("I was unable to view your Server Bans! Please ensure I have the ``Ban Members`` role permission.")

            for ban in bans:
                user = ban.user
                user_data = await self.r.db("bloxlink").table("users").get(str(user.id)).run() or {}
                roblox_data = await extract_accounts(user_data, resolve_to_users=False, reverse_search=True)

                for roblox_id, discord_accounts in roblox_data.items():
                    for discord_id in discord_accounts:
                        ban_evader = guild.get_member(int(discord_id))

                        if ban_evader:
                            ban_evaders[user] = ban_evaders.get(user) or []

                            if ban_evader not in ban_evaders[user]:
                                ban_evaders[user].append(ban_evader)

            if ban_evaders:
                now = datetime.datetime.now()
                ban_evaders_file = ["Report generated by Bloxlink", now.strftime("%d %B %Y, %H:%M:%S"), ""]
                successful, failed = [], []

                for original_account, new_accounts in ban_evaders.items():
                    accounts_str = [str(x) + " " + f'({x.id})' for x in new_accounts]

                    ban_evaders_file.append(f"Banned account: {original_account} ({original_account.id}), "
                                            f"new account(s) in server: {', '.join(accounts_str)}")

                    if action in ("kick", "ban"):
                        for discord_account in new_accounts:
                            if action == "ban":
                                try:
                                    await guild.ban(discord_account, reason=f"{author} ran !bansearch and chose to ban ban-evaders")
                                except (Forbidden, NotFound):
                                    failed.append(f"{str(discord_account)} ({discord_account.id})")
                                else:
                                    successful.append(f"{str(discord_account)} ({discord_account.id})")

                            elif action == "kick":
                                try:
                                    await guild.kick(discord_account, reason=f"{author} ran !bansearch and chose to kick ban-evaders")
                                except (Forbidden, NotFound):
                                    failed.append(f"{str(discord_account)} ({discord_account.id})")
                                else:
                                    successful.append(f"{str(discord_account)} ({discord_account.id})")


                final_buffer = StringIO("\r\n\n".join(ban_evaders_file))

                await response.send(f"These members in your server have an account which is banned.", files=[
                    File(final_buffer, filename=now.strftime("ban-evaders_%d-%m-%Y")),
                ])

                if successful:
                    succeeded_buffer = StringIO("\r\n\n".join(successful))

                    await response.send(f"These members were successfully actioned.", files=[
                        File(succeeded_buffer, filename=now.strftime(f"successful_{action}_%d-%m-%Y")),
                    ])

                    succeeded_buffer.close()

                if failed:
                    failed_buffer = StringIO("\r\n\n".join(failed))

                    await response.send(f"These members failed to be actioned.", files=[
                        File(failed_buffer, filename=now.strftime(f"failed_{action}_%d-%M-%Y")),
                    ])

                    failed_buffer.close()

                final_buffer.close()

            else:
                await response.send("There are no ban evaders in your server! :tada:")

        finally:
            cooldown = 120

            if self.redis:
                await self.redis.set(redis_cooldown_key, 3, ex=cooldown)


    async def __main__(self, CommandArgs):
        response = CommandArgs.response
        action = CommandArgs.parsed_args["action"]
        guild = CommandArgs.message.guild
        author = CommandArgs.message.author

        if self.redis:
            redis_cooldown_key = self.REDIS_COOLDOWN_KEY.format(release=RELEASE, id=guild.id)
            on_cooldown = await self.cache.get(redis_cooldown_key)

            if on_cooldown:
                cooldown_time = math.ceil(await self.redis.ttl(redis_cooldown_key)/60)

                if not cooldown_time or cooldown_time == -1:
                    await self.redis.delete(redis_cooldown_key)
                    on_cooldown = None

                if on_cooldown:
                    if on_cooldown == 1:
                        raise Message(f"This server is still queued.")
                    elif on_cooldown == 2:
                        raise Message("This server's scan is currently running.")
                    elif on_cooldown == 3:
                        cooldown_time = math.ceil(await self.redis.ttl(redis_cooldown_key)/60)

                        raise Message(f"This server has an ongoing cooldown! You must wait **{cooldown_time}** more minutes.")

            await self.redis.set(redis_cooldown_key, 1, ex=86400)
            await self.process_guild(guild, author, action, response)
